version: '3.4'

services:
  sample.api:
    image: sampleapi
    build:
      context: .
      dockerfile: SampleAPI/Dockerfile
    networks:
      test-network:
        aliases:
          - sample.st.dev
    ports:
      - "8000:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=localhost
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  sample.caller.api:
    image: samplecallerapi
    build:
      context: .
      dockerfile: SampleCallerApi/Dockerfile
    depends_on:
      - sample.api
    networks:
      - test-network
    ports:
      - "8001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=localhost
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

networks:
  test-network:
